import csv
import io
from datetime import datetime, timedelta
from celery import Celery
from celery.schedules import crontab
from controller.extensions import db
from controller.models import User, Booking, Trek
from sqlalchemy import func, extract
from mail import send_html_email

celery_app = Celery('tasks', broker='redis://localhost:6379/0')

celery_app.conf.update(
    timezone='Asia/Kolkata',  # Standard tzdata name for IST
    enable_utc=False,
    beat_schedule={
        'daily-trek-reminder-8am': {
            'task': 'tasks.daily_trek_reminder',
            'schedule': crontab(hour=8, minute=0), # Fires exactly at 8:00 AM IST
        },
        'monthly-admin-report-1st': {
            'task': 'tasks.monthly_admin_report',
            'schedule': crontab(day_of_month='1', hour=9, minute=0), # 1st of month at 9:00 AM
        }
    }
)


# ==========================================================
# 1. ASYNC: CSV HISTORY EXPORT (In-Memory)
# ==========================================================
@celery_app.task(name='tasks.export_history_csv')
def export_history_csv(user_id, user_email, user_name):
    from app import create_app
    app = create_app()
    with app.app_context():
        bookings = Booking.query.filter_by(user_id=user_id).all()
        
        # Build CSV strictly in RAM
        csv_buffer = io.StringIO()
        writer = csv.writer(csv_buffer)
        writer.writerow(['Booking ID', 'Trek Name', 'Date Secured', 'Payment Status', 'Lifecycle Status', 'Total Paid (INR)'])
        
        for b in bookings:
            writer.writerow([
                f"#APX-B{b.booking_id}", b.trek.trek_name if b.trek else "N/A", 
                b.booking_date.strftime("%Y-%m-%d"), b.payment_status, b.status, b.total_amount
            ])
            
        csv_string_data = csv_buffer.getvalue()
        csv_buffer.close() # Free memory
        
        # Curated HTML Template
        html_body = f"""
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #0b1f15; color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #198754;">
            <div style="background-color: #198754; padding: 20px; text-align: center;">
                <h2 style="margin: 0; color: #ffffff; letter-spacing: 1px;">Apex Expeditions Data Core</h2>
            </div>
            <div style="padding: 30px;">
                <h3 style="margin-top: 0;">Hello {user_name},</h3>
                <p style="color: #a0aec0; line-height: 1.6;">Your requested expedition history matrix has been successfully compiled from our secure database servers.</p>
                <p style="color: #a0aec0; line-height: 1.6;">Attached to this transmission is the CSV telemetry file containing your complete route logs, financial transactions, and basecamp authorizations.</p>
                <br>
                <p style="color: #a0aec0; font-size: 12px; border-top: 1px solid #2d3748; padding-top: 15px;">Securely generated by the Apex Automated Worker Matrix.</p>
            </div>
        </div>
        """
        
        filename = f"Apex_History_Log_{datetime.now().strftime('%Y%m%d')}.csv"
        send_html_email(user_email, "Your Expedition History CSV is Ready", html_body, filename, csv_string_data)


# ==========================================================
# 2. SCHEDULED BEAT: DAILY REMINDER WITH CTA
# ==========================================================
@celery_app.task(name='tasks.daily_trek_reminder')
def daily_trek_reminder():
    from app import create_app
    app = create_app()
    with app.app_context():
        
        tomorrow = datetime.now().date() + timedelta(days=1)
        upcoming_treks = Trek.query.filter(db.func.date(Trek.start_date) == tomorrow).all()
        
        for trek in upcoming_treks:
            # Safely resolve Staff Guide name
            guide_name = "Assigned at Basecamp"
            if trek.assigned_staff_id:
                guide_user = User.query.get(trek.assigned_staff_id)
                if guide_user: guide_name = guide_user.name

            bookings = Booking.query.filter_by(trek_id=trek.trek_id, status='Booked').all()
            for b in bookings:
                html_body = f"""
                <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background-color: #0f172a; color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #1e293b;">
                    <div style="background-color: #198754; padding: 25px; text-align: center;">
                        <h2 style="margin: 0; color: #ffffff; letter-spacing: 1px;">Final Departure Briefing </h2>
                        <p style="margin: 5px 0 0 0; color: #e2e8f0; font-size: 14px;">Your expedition begins tomorrow.</p>
                    </div>
                    
                    <div style="padding: 30px;">
                        <h3 style="margin-top: 0; color: #f8f9fa;">Greetings {b.user.name},</h3>
                        <p style="color: #cbd5e1; line-height: 1.6;">We are exactly 24 hours out from our departure. This automated message serves as your final verification checkpoint before we break ground. Please review your tactical trail manifest below and ensure you arrive at the designated basecamp by 6:00 AM sharp.</p>
                        
                        <div style="background-color: #1e293b; border-radius: 8px; padding: 20px; margin: 25px 0; border-left: 4px solid #10b981;">
                            <h4 style="margin: 0 0 15px 0; color: #7bf1a8; border-bottom: 1px solid #334155; padding-bottom: 10px;">Expedition Manifest</h4>
                            
                            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                                <tr>
                                    <td style="padding: 8px 0; color: #94a3b8;">Route Name</td>
                                    <td style="padding: 8px 0; color: #ffffff; text-align: right; font-weight: bold;">{trek.trek_name}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; color: #94a3b8;">Location Grid</td>
                                    <td style="padding: 8px 0; color: #ffffff; text-align: right;">{trek.location}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; color: #94a3b8;">Duration</td>
                                    <td style="padding: 8px 0; color: #ffffff; text-align: right;">{trek.duration_days} Days</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; color: #94a3b8;">Party Headcount</td>
                                    <td style="padding: 8px 0; color: #ffffff; text-align: right;">{b.number_of_persons} Explorers</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; color: #94a3b8;">Assigned Guide</td>
                                    <td style="padding: 8px 0; color: #7bf1a8; text-align: right;">👨‍✈️ {guide_name}</td>
                                </tr>
                            </table>
                        </div>
                        
                        <div style="text-align: center; margin-top: 35px;">
                            <a href="http://localhost:5173/portal/trekker/bookings" style="background-color: #ffffff; color: #0f172a; padding: 12px 30px; text-decoration: none; border-radius: 50px; font-weight: bold; font-size: 14px;">Show Details</a>
                        </div>
                    </div>
                </div>
                """
                send_html_email(b.user.email, f"Apex Departure: {trek.trek_name} Starts Tomorrow", html_body)
                
                
# ==========================================================
# 3. SCHEDULED BEAT: MONTHLY ADMIN REPORT
# ==========================================================
@celery_app.task(name='tasks.monthly_admin_report')
def monthly_admin_report():
    from app import create_app
    app = create_app()
    with app.app_context():
        now = datetime.now() 
        month_name = now.strftime('%B %Y')
        
        # 1. FETCH MONTHLY KPI (Key Performance Indicators)
        # Revenue this month
        monthly_revenue = db.session.query(func.sum(Booking.total_amount)).filter(
            extract('month', Booking.created_at) == now.month,
            extract('year', Booking.created_at) == now.year,
            Booking.payment_status == 'Paid'
        ).scalar() or 0

        # New Routes registered this month
        new_routes_count = Trek.query.filter(
            extract('month', Trek.created_at) == now.month,
            extract('year', Trek.created_at) == now.year
        ).count()
    
        # Participants accommodated this month (sum of number_of_persons in Bookings)
        participants_accommodated_count = db.session.query(func.sum(Booking.number_of_persons)).filter(
            extract('month', Booking.created_at) == now.month,
            extract('year', Booking.created_at) == now.year,
            Booking.payment_status == 'Paid'  # Or Booking.status == 'Booked', depending on your models
        ).scalar() or 0

        # New Trekkers registered this month
        new_users_count = User.query.filter(
            User.role.has(name='trekker'),
            extract('month', User.created_at) == now.month,
            extract('year', User.created_at) == now.year
        ).count()

        # 2. POPULAR TREK OF THE MONTH
        popular_trek_query = db.session.query(
            Trek.trek_name, func.count(Booking.booking_id).label('b_count')
        ).join(Booking).filter(
            extract('month', Booking.created_at) == now.month
        ).group_by(Trek.trek_id).order_by(db.desc('b_count')).first()

        popular_trek_name = popular_trek_query[0] if popular_trek_query else "N/A"

        # 3. RECENT LOGS GLIMPSE (Latest 5 bookings)
        recent_bookings = Booking.query.order_by(Booking.created_at.desc()).limit(5).all()
        logs_html = ""
        for b in recent_bookings:
            logs_html += f"""
            <tr style="border-bottom: 1px solid #2d3748;">
                <td style="padding: 10px; color: #a0aec0; font-size: 13px;">#APX-{b.booking_id}</td>
                <td style="padding: 10px; color: #ffffff; font-size: 13px;">{b.trek.trek_name}</td>
                <td style="padding: 10px; color: #7bf1a8; font-size: 13px; text-align: right;">₹{b.total_amount}</td>
            </tr>"""

        # 4. CURATED HTML TEMPLATE
        html_body = f"""
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 650px; margin: 0 auto; background-color: #0f172a; color: #ffffff; border-radius: 16px; overflow: hidden; border: 1px solid #1e293b;">
            <div style="background: linear-gradient(90deg, #198754, #10b981); padding: 30px; text-align: center;">
                <h1 style="margin: 0; font-size: 24px; letter-spacing: 1px;">Admin Executive Summary</h1>
                <p style="margin: 5px 0 0 0; opacity: 0.8;">Platform Performance for {month_name}</p>
            </div>

            <div style="padding: 30px;">
                <div style="background-color: #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 25px;">
                    <h4 style="margin: 0 0 10px 0; color: #7bf1a8;">🌙 Monthly Perspective</h4>

                    <p style="margin: 0 0 15px 0;">We have continued to operate effectively and expand our map this cycle. Here are your operational highlights:</p>
    
                    <ul style="margin: 0; padding-left: 20px; list-style-type: circle;">
                        <li style="margin-bottom: 10px;">
                            <span style="color: #cbd5e1;">Trail Expansion:</span> 
                            <strong style="color: #ffffff;">{new_routes_count}</strong> new routes.
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span style="color: #cbd5e1;">Field Operations:</span> 
                            <strong style="color: #ffffff;">{participants_accommodated_count}</strong> participants.
                        </li>
                        <li style="margin-bottom: 10px;">
                            <span style="color: #cbd5e1;">Community Growth:</span> 
                            <strong style="color: #ffffff;">{new_users_count}</strong> new explorers.
                        </li>
                        <li style="margin-bottom: 0;">
                            <span style="color: #cbd5e1;">Top Destination:</span> 
                            The <strong style="color: #ffffff;">{popular_trek_name}</strong> trail .
                        </li>
                    </ul>
                </div>

                <table style="width: 100%; margin-bottom: 30px;">
                    <tr>
                        <td style="width: 50%; padding-right: 10px;">
                            <div style="border: 1px solid #334155; padding: 15px; border-radius: 10px; text-align: center;">
                                <span style="font-size: 12px; color: #94a3b8; text-transform: uppercase;">Monthly Revenue</span>
                                <div style="font-size: 20px; font-weight: bold; color: #7bf1a8; margin-top: 5px;">₹{monthly_revenue:,.0f}</div>
                            </div>
                        </td>
                        <td style="width: 50%; padding-left: 10px;">
                            <div style="border: 1px solid #334155; padding: 15px; border-radius: 10px; text-align: center;">
                                <span style="font-size: 12px; color: #94a3b8; text-transform: uppercase;">Routes Deployed</span>
                                <div style="font-size: 20px; font-weight: bold; color: #ffffff; margin-top: 5px;">{new_routes_count}</div>
                            </div>
                        </td>
                    </tr>
                </table>

                <h4 style="margin: 0 0 15px 0; border-bottom: 1px solid #334155; padding-bottom: 10px;">📋 Recent Activity Logs</h4>
                <table style="width: 100%; border-collapse: collapse;">
                    {logs_html}
                </table>

                <div style="text-align: center; margin-top: 40px;">
                    <a href="http://localhost:5173/portal/admin/dashboard" 
                       style="background-color: #ffffff; color: #0f172a; padding: 14px 35px; text-decoration: none; border-radius: 50px; font-weight: bold; font-size: 14px; display: inline-block; box-shadow: 0 4px 12px rgba(0,0,0,0.3);">
                       Access Command Center Analytics
                    </a>
                </div>
            </div>
            
            <div style="background-color: #1e293b; padding: 15px; text-align: center; font-size: 11px; color: #64748b;">
                System generated report. Confidential administrative data.
            </div>
        </div>
        """
        
        admin = User.query.filter(User.role.has(name='admin')).first()

        send_html_email(admin.email, f"Platform Audit Report: {month_name}", html_body)